// react-todo/src/Todo.js
import React from 'react'

export const Todo = ({ name, done, onCheck, onRemove }) => (
    <div>
        <input
            type={'checkbox'}
            checked={done}
            onChange={(e) => onCheck(e.target.checked)}
        />
        <span className={done ? 'done' : ''}>{name}</span>
        <input
            className={'remove'}
            type={'button'}
            value={'x'}
            onClick={onRemove}
        />
    </div>
)

// angular-todo/src/app/todo/todo.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core'
import { Todo } from '../model'

@Component({
    selector: 'todo',
    templateUrl: './todo.component.html',
})
export class TodoComponent {
    @Input()
    todo: Todo

    @Output()
    onRemove = new EventEmitter<Todo>()

    remove = () => this.onRemove.emit(this.todo)
}

<div>
  <input
    type="checkbox"
    [(ngModel)]="todo.done"
  />
  <span [class.done]="todo.done">{{todo.name}}</span>
  <input class="remove" type="button" value="x" (click)="remove()"/>
</div>
