// vue-todo/src/components/TodoGroup.vue
<template>
    <div>
        <div class="todo-group__header">
            <span class="pointer">X</span>
        </div>
        <div class="todo-group__body">
            <h3>{{ group.name }}</h3>
            <Todo
                v-for="todo in group.todos"
                :todo="todo"
                :key="todo.name"
                @on-todo-change="changeTodo"
                @on-todo-remove="removeTodo"
            />
            <input
                type="text"
                placeholder="Nowa rzecz"
                v-model="newTodo.name"
            />
            <input
                class="btn"
                type="button"
                value="Dodaj nową rzecz!"
                @click="addNewTodo"
            />
        </div>
    </div>
</template>

<script>
import Todo from './Todo'
export default {
    name: 'TodoGroup',
    components: { Todo },
    data: () => ({
        newTodo: { name: '', done: false },
    }),
    props: {
        group: Object,
        onNewTodoAdd: Function,
        onTodoChange: Function,
        onTodoRemove: Function,
    },
    methods: {
        addNewTodo: function () {
            this.$emit('on-new-todo-add', this.group, this.newTodo)
            this.newTodo = { name: '', done: false }
        },
        changeTodo: function (todo, done) {
            this.$emit('on-todo-change', this.group, todo, done)
        },
        removeTodo: function (todo) {
            this.$emit('on-todo-remove', this.group, todo)
        },
    },
}
</script>

// angular-todo/src/app/todo-group/todo-group.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core'
import { Todo, TodoGroup } from '../model'

@Component({
    selector: 'todo-group',
    templateUrl: './todo-group.component.html',
})
export class TodoGroupComponent {
    newTodo: string

    @Input()
    group: TodoGroup

    @Output()
    onGroupRemove = new EventEmitter<TodoGroup>()

    removeTodo = (todo: Todo) =>
        (this.group.todos = this.group.todos.filter((el) => el !== todo))

    removeGroup = () => this.onGroupRemove.emit(this.group)

    addNewTodo = () => {
        this.group.todos.push({
            name: this.newTodo,
            done: false,
        })
        this.newTodo = ''
    }
}

<div>
    <div class="todo-group__header">
        <span class="pointer" (click)="removeGroup()">X</span>
    </div>
    <div class="todo-group__body">
        <h3>{{ group.name }}</h3>
        <todo
            *ngFor="let todo of group.todos"
            [todo]="todo"
            (onRemove)="removeTodo($event)"
        ></todo>
        <input type="text" placeholder="Nowa rzecz" [(ngModel)]="newTodo" />
        <input
            class="btn"
            type="button"
            value="Dodaj nową rzecz!"
            (click)="addNewTodo()"
        />
    </div>
</div>
