// vue-todo/src/components/AddNewTodo.vue
<template>
    <div class="todo-group__body">
        <h3>Dodaj karteczkę!</h3>
        <input type="text" placeholder="Nazwa" />
        <input type="text" placeholder="Do zrobienia!" />
        <input class="btn" type="button" value="Dodaj nową rzecz!" />
        <input class="btn" type="button" value="Dodaj!" />
    </div>
</template>

<script>
export default {
    name: 'AddNewTodo',
}
</script>

// react-todo/src/AddNewTodo.js
import React, { useState } from 'react'

export const AddNewTodo = ({ onAdd }) => {
    const [name, setName] = useState('')
    const [todos, setTodos] = useState([])
    const onNameChange = (e) => setName(e.target.value)
    const onTodoChange = (i) => (e) =>
        setTodos(
            todos.map((todo, index) => (i === index ? e.target.value : todo))
        )
    const onNewTodoAdd = () => setTodos([...todos, ''])
    const onGroupAdd = () => {
        onAdd({
            name,
            todos: todos.map((todo) => ({
                name: todo,
                done: false,
            })),
        })
        setTodos([])
        setName('')
    }
    return (
        <div className={'todo-group__body'}>
            <h3>Dodaj karteczkę!</h3>
            <input
                type={'text'}
                value={name}
                onChange={onNameChange}
                placeholder={'Nazwa'}
            />
            {todos.map((todo, i) => (
                <input
                    key={i}
                    type={'text'}
                    value={todos[i]}
                    placeholder={'Do zrobienia!'}
                    onChange={onTodoChange(i)}
                />
            ))}
            <input
                className={'btn'}
                type={'button'}
                value={'Dodaj nową rzecz!'}
                onClick={onNewTodoAdd}
            />
            <input
                className={'btn'}
                type={'button'}
                value={'Dodaj!'}
                onClick={onGroupAdd}
            />
        </div>
    )
}
