// react-todo/src/Todo.js
import React from 'react'

export const Todo = ({ name, done, onCheck, onRemove }) => (
    <div>
        <input
            type={'checkbox'}
            checked={done}
            onChange={(e) => onCheck(e.target.checked)}
        />
        <span className={done ? 'done' : ''}>{name}</span>
        <input
            className={'remove'}
            type={'button'}
            value={'x'}
            onClick={onRemove}
        />
    </div>
)

// vue-todo/src/components/Todo.vue
<template>
    <div>
        <input type="checkbox" :checked="todo.done" />
        <span
            :class="{
                done: todo.done,
            }"
            >{{ todo.name }}</span
        >
        <input class="remove" type="button" value="x" />
    </div>
</template>

<script>
export default {
    name: 'Todo',
    props: {
        todo: Object,
    },
}
</script>
