// vue-todo/src/components/AddNewTodo.vue
<template>
    <div class="todo-group__body">
        <h3>Dodaj karteczkę!</h3>
        <input type="text" placeholder="Nazwa" v-model="group.name" />
        <input
            type="text"
            placeholder="Do zrobienia!"
            v-for="(todo, i) in group.todos"
            v-model="todo.name"
            :key="i"
        />
        <input
            class="btn"
            type="button"
            value="Dodaj nową rzecz!"
            @click="addNewTodo"
        />
        <input class="btn" type="button" value="Dodaj!" @click="addGroup"/>
    </div>
</template>

<script>
export default {
    name: 'AddNewTodo',
    data: () => ({
        group: {
            name: '',
            todos: [],
        },
    }),
    methods: {
        addNewTodo: function () {
            this.group.todos.push({ name: '', done: false })
        },
        addGroup: function() {
            this.$emit('on-group-add', this.group)
            this.group = {
                name: '',
                todos: []
            }
        }
    },
    props: {
        onGroupAdd: Function
    }
}
</script>

// angular-todo/src/app/add-new-todo/add-new-todo.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core'
import { TodoGroup } from '../model'

@Component({
    selector: 'add-new-todo',
    templateUrl: './add-new-todo.component.html',
})
export class AddNewTodoComponent {
    group: TodoGroup = {
        todos: [],
        name: '',
    }

    @Output()
    onGroupAdd = new EventEmitter<TodoGroup>()

    addTodo = () =>
        this.group.todos.push({
            name: '',
            done: false,
        })

    addGroup = () => {
        this.onGroupAdd.emit(this.group)
        this.group = {
            todos: [],
            name: '',
        }
    }
}

<div class="todo-group__body">
    <h3>Dodaj karteczkę!</h3>
    <input type="text" placeholder="Nazwa" [(ngModel)]="group.name" />
    <input
        *ngFor="let todo of group.todos"
        type="text"
        placeholder="Do zrobienia!"
        [(ngModel)]="todo.name"
    />
    <input
        class="btn"
        type="button"
        value="Dodaj nową rzecz!"
        (click)="addTodo()"
    />
    <input class="btn" type="button" value="Dodaj!" (click)="addGroup()" />
</div>
